version: '3.9'
services:
  samplesamlidp:
    image: kristophjunge/test-saml-idp
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      - SIMPLESAMLPHP_SP_ENTITY_ID=http://localhost:3000/saml/metadata
      - SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE=http://localhost:3000/saml/callback
      - SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE=
    volumes:
      - "./_docker/users.php:/var/www/simplesamlphp/config/authsources.php"